{
  "cast": [
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [
        9648
      ],
      "id": 875687,
      "original_language": "en",
      "original_title": "Air",
      "overview": "Englishman hiking in rural Texas has a supernatural experience.",
      "popularity": 0.2459,
      "poster_path": "/w4VxJqVYFBD1Z0AASMe4f644TpB.jpg",
      "release_date": "2010-10-14",
      "title": "Air",
      "video": false,
      "vote_average": 6.3,
      "vote_count": 3,
      "character": "Tom",
      "credit_id": "6146771522df2e0046d882a6",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/9xc1xRBUgSDSQeWQ1oCFFz8gISN.jpg",
      "genre_ids": [
        99
      ],
      "id": 877657,
      "original_language": "en",
      "original_title": "Attack of the Hollywood Clichés!",
      "overview": "One-man armies, meet-cutes, casual strolls away from huge explosions — stars and industry insiders toast and roast these cinematic chestnuts and more.",
      "popularity": 3.5297,
      "poster_path": "/fmI1oIAwXjfX8LcZYT8Rs2rZe2R.jpg",
      "release_date": "2021-09-27",
      "title": "Attack of the Hollywood Clichés!",
      "video": false,
      "vote_average": 5.975,
      "vote_count": 121,
      "character": "Self - Actor",
      "credit_id": "614ddde25346610061a2a311",
      "order": 7,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/tfE55NmC3tF2U0DtZkAYKvUHn5k.jpg",
      "genre_ids": [
        28,
        12,
        18,
        36
      ],
      "id": 4515,
      "original_language": "en",
      "original_title": "Lions for Lambs",
      "overview": "Three stories told simultaneously in ninety minutes of real time: a Republican Senator who's a presidential hopeful gives an hour-long interview to a skeptical television reporter, detailing a strategy for victory in Afghanistan; two special forces ambushed on an Afghani ridge await rescue as Taliban forces close in; a poli-sci professor at a California college invites a student to re-engage.",
      "popularity": 2.2829,
      "poster_path": "/tpwq5AHgj13uBE06B07xWqWQV5i.jpg",
      "release_date": "2007-10-22",
      "title": "Lions for Lambs",
      "video": false,
      "vote_average": 6,
      "vote_count": 803,
      "character": "Todd Hayes",
      "credit_id": "52fe43c7c3a36847f806f075",
      "order": 3,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/vBw4z7l3NI32th7nR34zqRgdvXS.jpg",
      "genre_ids": [
        12,
        14,
        9648
      ],
      "id": 8054,
      "original_language": "en",
      "original_title": "The Imaginarium of Doctor Parnassus",
      "overview": "After a carnival troupe saves his life, a man agrees to help its immortal leader collect five souls and win a bet with the devil.",
      "popularity": 1.927,
      "poster_path": "/DtrqQHa0wT9AWrk2WA9beROJJx.jpg",
      "release_date": "2009-10-01",
      "title": "The Imaginarium of Doctor Parnassus",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 2796,
      "character": "Anton",
      "credit_id": "52fe448ec3a36847f809cd49",
      "order": 3,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/jovVe4UGpmQEAE6ZEmV5xa6Kk1f.jpg",
      "genre_ids": [
        18,
        10749,
        36
      ],
      "id": 12184,
      "original_language": "en",
      "original_title": "The Other Boleyn Girl",
      "overview": "A sumptuous and sensual tale of intrigue, romance and betrayal set against the backdrop of a defining moment in European history: two beautiful sisters, Anne and Mary Boleyn, driven by their family's blind ambition, compete for the love of the handsome and passionate King Henry VIII.",
      "popularity": 4.3831,
      "poster_path": "/q2lgC8mmAltWTkbqPM8n5EYF4XL.jpg",
      "release_date": "2008-02-28",
      "title": "The Other Boleyn Girl",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 2165,
      "character": "Francis Weston",
      "credit_id": "52fe44c79251416c75040907",
      "order": 13,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/4t8IXJF4umwCfbdpeKLvlN3zkKp.jpg",
      "genre_ids": [
        10749,
        18
      ],
      "id": 1100099,
      "original_language": "en",
      "original_title": "We Live in Time",
      "overview": "An up-and-coming chef and a recent divorcée find their lives forever changed when a chance encounter brings them together, in a decade-spanning, deeply moving romance.",
      "popularity": 4.89,
      "poster_path": "/oeDNBgnlGF6rnyX1P1K8Vl2f3lW.jpg",
      "release_date": "2024-10-10",
      "title": "We Live in Time",
      "video": false,
      "vote_average": 7.255,
      "vote_count": 1108,
      "character": "Tobias Durand",
      "credit_id": "64109b4bb42242007d71cf44",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/ppf18IfACeWmkObqyjrhmNiL6G4.jpg",
      "genre_ids": [
        18,
        10749,
        878
      ],
      "id": 42188,
      "original_language": "en",
      "original_title": "Never Let Me Go",
      "overview": "As children, Kathy, Ruth, and Tommy spend their childhood at an idyllic and secluded English boarding school. As they grow into adults, they must come to terms with the complexity and strength of their love for one another while also preparing for the haunting reality awaiting them.",
      "popularity": 5.1444,
      "poster_path": "/8F0r5ng9Fp60OhzQfR5v33fppq.jpg",
      "release_date": "2010-03-18",
      "title": "Never Let Me Go",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 2387,
      "character": "Tommy D.",
      "credit_id": "52fe45f2c3a36847f80e3c45",
      "order": 2,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/gCPaaz5fkbHBaU2DIK2rhNIIxZF.jpg",
      "genre_ids": [
        80,
        18
      ],
      "id": 14748,
      "original_language": "en",
      "original_title": "Boy A",
      "overview": "Freed after a lengthy term in a juvenile detention center, convicted child killer Jack Burridge finds work as a deliveryman and begins dating co-worker Michelle. While out on the road one day, Jack notices a distressed child, and, after reuniting the girl with her family, becomes a local celebrity. But when a local newspaper unearths his past, Jack must cope with the anger of citizens who fear for the safety of their children.",
      "popularity": 4.5357,
      "poster_path": "/wrQQUjeiHFPvTfaaB3vtNLLZ8kv.jpg",
      "release_date": "2008-07-23",
      "title": "Boy A",
      "video": false,
      "vote_average": 7.109,
      "vote_count": 478,
      "character": "Jack Burridge",
      "credit_id": "52fe46159251416c7506c899",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/lJDbJ5JgsNtoeUWb7PX1Lji2uou.jpg",
      "genre_ids": [
        10749,
        878,
        18
      ],
      "id": 37058,
      "original_language": "en",
      "original_title": "I'm Here",
      "overview": "A library assistant plods through an ordinary life in LA until a chance meeting opens his eyes to the power of creativity and ultimately, love. When this new life and love begin to fall apart, he discovers he has a lot to give. This short film proves that ordinary is no place to be.",
      "popularity": 2.4398,
      "poster_path": "/1jq9zUwPIFGid3BMrLLcm3YY2nY.jpg",
      "release_date": "2010-03-01",
      "title": "I'm Here",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 184,
      "character": "Sheldon",
      "credit_id": "52fe46269251416c9104ad35",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/tyQo080tijexyUHBvWPwQt26bZa.jpg",
      "genre_ids": [
        28,
        12,
        878
      ],
      "id": 634649,
      "original_language": "en",
      "original_title": "Spider-Man: No Way Home",
      "overview": "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
      "popularity": 19.4936,
      "poster_path": "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
      "release_date": "2021-12-15",
      "title": "Spider-Man: No Way Home",
      "video": false,
      "vote_average": 7.937,
      "vote_count": 21291,
      "character": "Peter Parker / Spider-Man",
      "credit_id": "61b891dd1f3319006121ecd1",
      "order": 11,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/65D7t8wgZFpjOTvIp1HQvHFY0fC.jpg",
      "genre_ids": [
        18
      ],
      "id": 37799,
      "original_language": "en",
      "original_title": "The Social Network",
      "overview": "In 2003, Harvard undergrad and computer programmer Mark Zuckerberg begins work on a new concept that eventually turns into the global social network known as Facebook. Six years later, Mark is one of the youngest billionaires ever, but his unprecedented success leads to both personal and legal complications when he ends up on the receiving end of two lawsuits, one involving his former friend.",
      "popularity": 8.2904,
      "poster_path": "/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
      "release_date": "2010-10-01",
      "title": "The Social Network",
      "video": false,
      "vote_average": 7.371,
      "vote_count": 12747,
      "character": "Eduardo Saverin",
      "credit_id": "52fe466f9251416c910546d7",
      "order": 1,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [
        99,
        10402,
        18
      ],
      "id": 929038,
      "original_language": "en",
      "original_title": "Honoring a Broadway Legacy: Behind the Scenes of tick, tick...Boom!",
      "overview": "Go deep inside the film tick, tick...BOOM! with director Lin-Manuel Miranda, actor Andrew Garfield and the rest of the film's acclaimed ensemble. The award-winning biopic tells the story of the late Tony Award®-winning legend Jonathan Larson, an artist at a crossroads desperate to tell his story.",
      "popularity": 0.3826,
      "poster_path": "/1SVZiOwRb0vjAYufemgdRfAyy74.jpg",
      "release_date": "2022-01-19",
      "title": "Honoring a Broadway Legacy: Behind the Scenes of tick, tick...Boom!",
      "video": false,
      "vote_average": 7.833,
      "vote_count": 6,
      "character": "Self",
      "credit_id": "61e8df49a1c59d001c7d5581",
      "order": 3,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/k0hlAzTryCYX1O1LyC6P8tAa8s0.jpg",
      "genre_ids": [
        28,
        12,
        878
      ],
      "id": 102382,
      "original_language": "en",
      "original_title": "The Amazing Spider-Man 2",
      "overview": "For Peter Parker, life is busy. Between taking out the bad guys as Spider-Man and spending time with the person he loves, Gwen Stacy, high school graduation cannot come quickly enough. Peter has not forgotten about the promise he made to Gwen’s father to protect her by staying away, but that is a promise he cannot keep. Things will change for Peter when a new villain, Electro, emerges, an old friend, Harry Osborn, returns, and Peter uncovers new clues about his past.",
      "popularity": 14.3503,
      "poster_path": "/dGjoPttcbKR5VWg1jQuNFB247KL.jpg",
      "release_date": "2014-04-16",
      "title": "The Amazing Spider-Man 2",
      "video": false,
      "vote_average": 6.524,
      "vote_count": 13836,
      "character": "Spider-Man / Peter Parker",
      "credit_id": "52fe4a07c3a36847f81b477b",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/OKR5JJmayeCQ2kAFyGdCfdtVQb.jpg",
      "genre_ids": [
        35,
        18,
        53
      ],
      "id": 155776,
      "original_language": "en",
      "original_title": "Heroes and Demons",
      "overview": "Gripping thriller drama with fantastic all-star cast: Six different stories about crooks, misfits, heroes and their determination to overcome the destiny. Stories about intolerance, hopelessness, betrayal, despair, and the unpredictable.",
      "popularity": 3.7772,
      "poster_path": "/bGwEuV6u91naC6g3c1983rDI5uW.jpg",
      "release_date": "2011-05-11",
      "title": "Heroes and Demons",
      "video": false,
      "vote_average": 6.778,
      "vote_count": 18,
      "character": "Tom",
      "credit_id": "52fe4b899251416c910ddaff",
      "order": 12,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/tObVe1R7JnO3VXBvAOWTEPmmegu.jpg",
      "genre_ids": [
        99
      ],
      "id": 961651,
      "original_language": "en",
      "original_title": "Spider-Man: All Roads Lead to No Way Home",
      "overview": "JB Smoove and Martin Starr host a celebration of 20 years of \"Spider-Man\" movies, from the Sam Raimi trilogy to Marc Webb's movies and the trio from Jon Watts.",
      "popularity": 2.3045,
      "poster_path": "/e2LLmI5wKIrWGAy9Of3yyWu7Szn.jpg",
      "release_date": "2022-05-03",
      "title": "Spider-Man: All Roads Lead to No Way Home",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 91,
      "character": "Self",
      "credit_id": "6279b4f56f9746009b79cbad",
      "order": 1,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [
        10402,
        36
      ],
      "id": 978109,
      "original_language": "en",
      "original_title": "Instrumental",
      "overview": "It is based on concert pianist James Rhodes' memoir, which explores the legacy of the sexual abuse he suffered as a child, including a litany of mental health issues, and how music proved his salvation.",
      "popularity": 1.6732,
      "poster_path": null,
      "release_date": "",
      "title": "Instrumental",
      "video": false,
      "vote_average": 0,
      "vote_count": 0,
      "character": "James Rhodes",
      "credit_id": "6287f6e3ec455274c4be5676",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/HVcza6tJtWFrLriuh3Ano4Vt46.jpg",
      "genre_ids": [
        28,
        12,
        878
      ],
      "id": 1930,
      "original_language": "en",
      "original_title": "The Amazing Spider-Man",
      "overview": "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
      "popularity": 10.9779,
      "poster_path": "/jexoNYnPd6vVrmygwF6QZmWPFdu.jpg",
      "release_date": "2012-06-23",
      "title": "The Amazing Spider-Man",
      "video": false,
      "vote_average": 6.723,
      "vote_count": 18058,
      "character": "Spider-Man / Peter Parker",
      "credit_id": "531325d5c3a368299b0040db",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/icCQi9Tnyx86C987IoIFchxqMof.jpg",
      "genre_ids": [
        18
      ],
      "id": 283235,
      "original_language": "en",
      "original_title": "99 Homes",
      "overview": "After his family is evicted from their home, proud and desperate construction worker Dennis Nash tries to win his home back by striking a deal with the devil and working for Rick Carver, the corrupt real estate broker who evicted him.",
      "popularity": 2.6113,
      "poster_path": "/6Zul5Spndok1WriSMfiyQFbAyLY.jpg",
      "release_date": "2015-09-25",
      "title": "99 Homes",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 800,
      "character": "Dennis Nash",
      "credit_id": "53ce96bfc3a3687761005233",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/cK4zqgIXBFWoaQ5Kmz8GdyHApIv.jpg",
      "genre_ids": [
        53,
        9648,
        80,
        18,
        10770
      ],
      "id": 291081,
      "original_language": "en",
      "original_title": "Red Riding: The Year of Our Lord 1974",
      "overview": "Yorkshire, 1974. Fear, mistrust and institutionalised police corruption are running riot. Rookie journalist Eddie Dunford is determined to search for the truth in an increasingly complex maze of lies and deceit surrounding the police investigation into a series of child abductions. When young Clare Kemplay goes missing, Eddie and his colleague, Barry, persuade their editor to let them investigate links with two similar abductions that draw them into a deadly world of secrecy, intimidation, shocking revelations and police brutality.",
      "popularity": 3.6467,
      "poster_path": "/1MGUwUFkcAKawdsT2q88Sdo2vv6.jpg",
      "release_date": "2009-11-11",
      "title": "Red Riding: The Year of Our Lord 1974",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 278,
      "character": "Eddie Dunford",
      "credit_id": "540c69120e0a262b3d0042dd",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/yGZKUg2EOLJ9YaPKSIDRITLZIX5.jpg",
      "genre_ids": [
        53,
        80,
        18,
        9648,
        10770
      ],
      "id": 291084,
      "original_language": "en",
      "original_title": "Red Riding: The Year of Our Lord 1980",
      "overview": "After 6 years of brutal murders, the West Yorkshire Police fear that they may have already interviewed The Ripper and let him back into the world to continue his reign of terror upon the citizens of Yorkshire. Assistant Chief Constable of the Manchester Police, Peter Hunter, is called in to oversee the West Yorkshire Police's Ripper investigation and see what they could have missed.",
      "popularity": 3.6439,
      "poster_path": "/8DeTSHV2gkT3HYTWb3o2Z8wKbIe.jpg",
      "release_date": "2009-11-11",
      "title": "Red Riding: The Year of Our Lord 1980",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 189,
      "character": "Eddie Dunford",
      "credit_id": "5549f60ec3a36841a9001ec6",
      "order": 18,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/5pN5TtSg8zjHTXhi1Rr63d0pWWE.jpg",
      "genre_ids": [
        53,
        80,
        18,
        9648,
        10770
      ],
      "id": 291092,
      "original_language": "en",
      "original_title": "Red Riding: The Year of Our Lord 1983",
      "overview": "Detective Chief Superintendent Maurice Jobson is forced to remember the very similar disappearance of Clare Kemplay, who was found dead in 1974, and the subsequent imprisonment of local boy Michael Myshkin. Washed-up local solicitor John Piggott becomes convinced of Myshkin's innocence and begins to fight on his behalf, unwittingly providing a catalyst for Jobson to start to right some wrongs.",
      "popularity": 3.0055,
      "poster_path": "/zyaV5xR5Ugsvf4An1JFVEmlkSB.jpg",
      "release_date": "2009-11-11",
      "title": "Red Riding: The Year of Our Lord 1983",
      "video": false,
      "vote_average": 7,
      "vote_count": 182,
      "character": "Eddie Dunford",
      "credit_id": "5549f75092514136fa000e42",
      "order": 16,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/vDKRMZGFTKP9nQolzeSB1rB1w6p.jpg",
      "genre_ids": [
        18,
        36,
        10752
      ],
      "id": 324786,
      "original_language": "en",
      "original_title": "Hacksaw Ridge",
      "overview": "WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first Conscientious Objector in American history to receive the Congressional Medal of Honor.",
      "popularity": 10.1877,
      "poster_path": "/wuz8TjCIWR2EVVMuEfBnQ1vuGS3.jpg",
      "release_date": "2016-10-07",
      "title": "Hacksaw Ridge",
      "video": false,
      "vote_average": 8.2,
      "vote_count": 14423,
      "character": "Desmond T. Doss",
      "credit_id": "55b9d30892514123d8003c55",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/yalstNcroVmzktW1bf0zsZzB0qo.jpg",
      "genre_ids": [
        10751,
        14,
        12
      ],
      "id": 1140521,
      "original_language": "en",
      "original_title": "The Magic Faraway Tree",
      "overview": "Soon after the Thompson family’s arrival in the countryside, the three children – Beth, Joe, and Fran – discover a magical tree and its extraordinary and eccentric residents, including Moonface, Silky, Dame Washalot, and Saucepan Man. At the top of the tree, they are transported to spectacular and fantastical lands and, through the joys and challenges of their adventures, the Thompsons learn to reconnect and value each other for the first time in years.",
      "popularity": 1.4267,
      "poster_path": "/iocbhAeD4DdlH4BwBidOgduEptA.jpg",
      "release_date": "2026-03-27",
      "title": "The Magic Faraway Tree",
      "video": false,
      "vote_average": 0,
      "vote_count": 0,
      "character": "Tim Thompson",
      "credit_id": "6634da34813cb6012487af52",
      "order": 1,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/8jHvHZPiw6h3Xfy0cv3m7H40O8e.jpg",
      "genre_ids": [
        18
      ],
      "id": 1265063,
      "original_language": "en",
      "original_title": "After the Hunt",
      "overview": "A college professor finds herself at a personal and professional crossroads when a star pupil levels an accusation against one of her colleagues, and a dark secret from her own past threatens to come to light.",
      "popularity": 77.9478,
      "poster_path": "/ryF8QPGUGlo8gRB4OYKb4J0r3aJ.jpg",
      "release_date": "2025-10-09",
      "title": "After the Hunt",
      "video": false,
      "vote_average": 6.016,
      "vote_count": 217,
      "character": "Hank Gibson",
      "credit_id": "66428f30978773b27892e0f3",
      "order": 2,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/r2z8ceIsg9ON8DIHTf6cMqnK3CL.jpg",
      "genre_ids": [
        80,
        18,
        9648
      ],
      "id": 396461,
      "original_language": "en",
      "original_title": "Under the Silver Lake",
      "overview": "Young and disenchanted Sam meets a mysterious and beautiful woman who's swimming in his building's pool one night. When she suddenly vanishes the next morning, Sam embarks on a surreal quest across Los Angeles to decode the secret behind her disappearance, leading him into the murkiest depths of mystery, scandal and conspiracy.",
      "popularity": 2.8344,
      "poster_path": "/771Ey73LqsE9ORJhQCI25rgMXS2.jpg",
      "release_date": "2018-08-08",
      "title": "Under the Silver Lake",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 1519,
      "character": "Sam",
      "credit_id": "572e494592514173a1000185",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/2tE0A6WjLowwQOUY8se1Xlf3O6U.jpg",
      "genre_ids": [
        18,
        36
      ],
      "id": 68730,
      "original_language": "en",
      "original_title": "Silence",
      "overview": "In the 17th century, two Portuguese Jesuit priests travel to Japan in an attempt to locate their mentor, who is rumored to have committed apostasy, and to propagate Catholicism.",
      "popularity": 3.2682,
      "poster_path": "/x5T0cQDYws0xRBVG4Q3wpcrcmax.jpg",
      "release_date": "2016-12-23",
      "title": "Silence",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 3187,
      "character": "Rodrigues",
      "credit_id": "575ebee292514116b60018a9",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/quVfDYktBYQfojgZ3E9pYrclGse.jpg",
      "genre_ids": [
        18,
        10749
      ],
      "id": 407445,
      "original_language": "en",
      "original_title": "Breathe",
      "overview": "Based on the true story of Robin, a handsome, brilliant and adventurous man whose life takes a dramatic turn when polio leaves him paralyzed.",
      "popularity": 1.6175,
      "poster_path": "/wLu2N0QVfSpk10RJ17HLHyRUmww.jpg",
      "release_date": "2017-10-13",
      "title": "Breathe",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 780,
      "character": "Robin Cavendish",
      "credit_id": "5790c9999251416bb40016d5",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/y0U6G434XjrDA9XIUZp0B78tRJR.jpg",
      "genre_ids": [
        18
      ],
      "id": 444459,
      "original_language": "en",
      "original_title": "National Theatre Live: Angels In America — Part One: Millennium Approaches",
      "overview": "The National Theatre's live theatrical production of Tony Kushner's two-part play 'Angels In America' about New Yorkers grappling with the AIDS crisis during the mid-1980s.",
      "popularity": 0.3835,
      "poster_path": "/pNfcp8uewaExjhVxRE37YCVYteV.jpg",
      "release_date": "2017-07-20",
      "title": "National Theatre Live: Angels In America — Part One: Millennium Approaches",
      "video": true,
      "vote_average": 8.1,
      "vote_count": 16,
      "character": "Prior Walter/The Man In The Park",
      "credit_id": "59008ed7c3a3680fec00ab2a",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/ayKo9NoR9BsosIvvTFEs2Bw7LRs.jpg",
      "genre_ids": [
        18
      ],
      "id": 444460,
      "original_language": "en",
      "original_title": "National Theatre Live: Angels In America — Part Two: Perestroika",
      "overview": "America in the mid-1980s. In the midst of the AIDS crisis and a conservative Reagan administration, New Yorkers grapple with life and death, love and sex, heaven and hell. This new staging of Tony Kushner's multi-award winning two-part play, Angels In America: A Gay Fantasia On National Themes, is directed by Olivier and Tony award winning director Marianne Elliott.",
      "popularity": 3.1736,
      "poster_path": "/jgZM8bYtAjNZ6HAjpJiuNJ1iq8t.jpg",
      "release_date": "2017-07-27",
      "title": "National Theatre Live: Angels In America — Part Two: Perestroika",
      "video": true,
      "vote_average": 8.1,
      "vote_count": 14,
      "character": "Prior Walter",
      "credit_id": "59009c15c3a368103a00b966",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/wrH0jFNI8Y4EsyFIuIPLS4WNhmc.jpg",
      "genre_ids": [
        35
      ],
      "id": 455498,
      "original_language": "en",
      "original_title": "Mumbo Jumbo",
      "overview": "In a misguided attempt to do something for the war on terror, self-styled suburban warriors Gool, Rube and Simmo are ready to carry out their first operation, but things don't go quite as they planned.",
      "popularity": 1.4127,
      "poster_path": "/vHwrC6pWv4NAqYOdW84bS0gQzZR.jpg",
      "release_date": "2005-07-07",
      "title": "Mumbo Jumbo",
      "video": false,
      "vote_average": 5,
      "vote_count": 1,
      "character": "Simmo",
      "credit_id": "59075a3ec3a3684ad70318a0",
      "order": 2,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/1mKIBEIryol4SFuE0qSwpVjIz1b.jpg",
      "genre_ids": [
        99
      ],
      "id": 451567,
      "original_language": "en",
      "original_title": "The Soul of War: Making 'Hacksaw Ridge'",
      "overview": "A comprehensive documentary detailing the making of 'Hacksaw Ridge', including the real-life people and story, casting, filming, special effects, stunts, and interviews with Mel Gibson, Andrew Garfield, and more. 'Hacksaw Ridge' is the epic and inspiring true story of Desmond Doss, an army medic and conscientious objector who, during one of the bloodiest battles of World War II, saved 75 men without firing or carrying a gun.",
      "popularity": 0.6756,
      "poster_path": "/zpAhD2QUyCz5bifjZUGVTabplMo.jpg",
      "release_date": "2017-02-21",
      "title": "The Soul of War: Making 'Hacksaw Ridge'",
      "video": true,
      "vote_average": 8.3,
      "vote_count": 28,
      "character": "Self",
      "credit_id": "59280c1cc3a368782d03544c",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/2im5xZdsVwNQbZsxP1qga2rHtkm.jpg",
      "genre_ids": [
        99
      ],
      "id": 154352,
      "original_language": "en",
      "original_title": "How Did They Ever Make a Movie of Facebook?",
      "overview": "This feature-length documentary about the making of \"The Social Network\" goes back and forth from the elements of storytelling and long rehearsals with the cast and crew, to the shooting itself capturing the extreme attention to detail, filming locations such as Boston and LA, and David Fincher's filmmaking process.",
      "popularity": 0.8607,
      "poster_path": "/gu83t0D0UYOGk2p9ufDjT5YllUa.jpg",
      "release_date": "2011-01-11",
      "title": "How Did They Ever Make a Movie of Facebook?",
      "video": true,
      "vote_average": 7.548,
      "vote_count": 21,
      "character": "Self / Eduardo Saverin",
      "credit_id": "5acb850ec3a3687dee01359b",
      "order": 3,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/9eYrq3NZq3WsCuYQS0q9zPr1eMf.jpg",
      "genre_ids": [
        35,
        18
      ],
      "id": 557950,
      "original_language": "en",
      "original_title": "Mainstream",
      "overview": "A young woman thinks she’s found a path to internet stardom when she starts making YouTube videos with a charismatic stranger  – until the dark side of viral celebrity threatens to ruin them both.",
      "popularity": 5.8435,
      "poster_path": "/9vTf02WXyldeKN4kfwZRwwI4XbG.jpg",
      "release_date": "2021-05-07",
      "title": "Mainstream",
      "video": false,
      "vote_average": 6.3,
      "vote_count": 361,
      "character": "Link",
      "credit_id": "5bd903f0925141155b003461",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [
        99
      ],
      "id": 587877,
      "original_language": "en",
      "original_title": "The Amazing Spider-Man T4 Premiere Special",
      "overview": "A TV special of the Amazing Spider-Man Premiere.",
      "popularity": 2.3152,
      "poster_path": null,
      "release_date": "2012-06-30",
      "title": "The Amazing Spider-Man T4 Premiere Special",
      "video": true,
      "vote_average": 7.8,
      "vote_count": 7,
      "character": "",
      "credit_id": "5c88ff3ac3a36864610b47b0",
      "order": 7,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/rskVKmBb83u7qbaASCxyJyLevkq.jpg",
      "genre_ids": [
        18,
        36
      ],
      "id": 601470,
      "original_language": "en",
      "original_title": "The Eyes of Tammy Faye",
      "overview": "From the 1960s to the 1980s, evangelist Jim Baker and his ambitious wife, Tammy Faye, rose from humble beginnings to build an empire based on big-time evangelical Christianity--only for the couple to fall from grace because of some all-too-human sins.",
      "popularity": 3.6118,
      "poster_path": "/h09nsvxZH72zx2U8gS8vrg47aRk.jpg",
      "release_date": "2021-09-17",
      "title": "The Eyes of Tammy Faye",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 650,
      "character": "Jim Bakker",
      "credit_id": "5cd551a20e0a265e0962ac7a",
      "order": 1,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/7eG8xwxDv25lBz0jdxsAsbcPHnp.jpg",
      "genre_ids": [
        99
      ],
      "id": 478253,
      "original_language": "en",
      "original_title": "Rite of Passage: The Amazing Spider-Man Reborn",
      "overview": "A documentary on the making of The Amazing Spider-Man (2012), featuring interviews with the cast and crew, as well as behind-the-scenes footage.",
      "popularity": 0.9327,
      "poster_path": "/3HLWPugHwRu6kSSaAalpgqHCd0Q.jpg",
      "release_date": "2012-11-09",
      "title": "Rite of Passage: The Amazing Spider-Man Reborn",
      "video": false,
      "vote_average": 7.3,
      "vote_count": 16,
      "character": "Self",
      "credit_id": "5da85e02944a570013257a83",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/rtIexdv2qF4c0cEbT8g1r2grLoC.jpg",
      "genre_ids": [
        99
      ],
      "id": 638453,
      "original_language": "en",
      "original_title": "The Wages of Heroism: Making The Amazing Spider-Man 2",
      "overview": "A documentary on the making of The Amazing Spider-Man 2 (2014), featuring interviews with the cast and crew, as well as behind-the-scenes footage.",
      "popularity": 1.6726,
      "poster_path": "/z5nm4z5dCS06mptUKKJpVBIq1aX.jpg",
      "release_date": "2014-08-19",
      "title": "The Wages of Heroism: Making The Amazing Spider-Man 2",
      "video": true,
      "vote_average": 7.4,
      "vote_count": 4,
      "character": "Self",
      "credit_id": "5d9f48a365686e0037625590",
      "order": 1,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/rKe3MR2u4ZZ0y9uKivzKJRrqBCe.jpg",
      "genre_ids": [
        18,
        10402
      ],
      "id": 537116,
      "original_language": "en",
      "original_title": "tick, tick... BOOM!",
      "overview": "On the brink of turning 30, a promising theater composer navigates love, friendship and the pressure to create something great before time runs out.",
      "popularity": 2.5247,
      "poster_path": "/DPmfcuR8fh8ROYXgdjrAjSGA0o.jpg",
      "release_date": "2021-11-11",
      "title": "tick, tick... BOOM!",
      "video": false,
      "vote_average": 7.609,
      "vote_count": 2220,
      "character": "Jonathan Larson",
      "credit_id": "5db9abbc2d37210015eb68a0",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [
        99
      ],
      "id": 794611,
      "original_language": "en",
      "original_title": "Martin Scorsese's Journey Into Silence",
      "overview": "A behind-the-scenes documentary on the making of Martin Scorsese's \"Silence.\"",
      "popularity": 0.5039,
      "poster_path": "/fpJ7IMvUbRTcA12UmISUsUt6kVw.jpg",
      "release_date": "2017-03-28",
      "title": "Martin Scorsese's Journey Into Silence",
      "video": false,
      "vote_average": 6,
      "vote_count": 1,
      "character": "Self",
      "credit_id": "60205cdf95c0af003e4e4381",
      "order": 1,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [
        18,
        36
      ],
      "id": 977942,
      "original_language": "en",
      "original_title": "The Uprising",
      "overview": "During the English Peasants' Revolt in 1381, a farmer becomes a leader of the rebellion against the Crown forces of a then-14-year-old King Richard II.",
      "popularity": 0.6592,
      "poster_path": "/xBn14Qxc7jYpl5GVVfKRMRE52k8.jpg",
      "release_date": "",
      "title": "The Uprising",
      "video": false,
      "vote_average": 0,
      "vote_count": 0,
      "character": "Wat Tyler",
      "credit_id": "6829e18b7e07d6ffec9e31fb",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [
        35,
        18
      ],
      "id": 1492198,
      "original_language": "en",
      "original_title": "Artificial",
      "overview": "Described as a comedic drama set in the world of artificial intelligence, around the period at OpenAI in 2023 that saw CEO Sam Altman fired and rehired in a matter of days.",
      "popularity": 6.874,
      "poster_path": "/6RKRs1vE0KPQIAtRseP9y6MNJe1.jpg",
      "release_date": "",
      "title": "Artificial",
      "video": false,
      "vote_average": 0,
      "vote_count": 0,
      "character": "Sam Altman",
      "credit_id": "683f316b1c9e61268c7f49be",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [],
      "id": 1518155,
      "original_language": "en",
      "original_title": "Voyagers",
      "overview": "",
      "popularity": 0.4527,
      "poster_path": null,
      "release_date": "",
      "title": "Voyagers",
      "video": false,
      "vote_average": 0,
      "vote_count": 0,
      "character": "Carl Sagan",
      "credit_id": "6881e97d1733da38d252a1f3",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [],
      "id": 1522577,
      "original_language": "en",
      "original_title": "Arcade Fire: We Exist",
      "overview": "Music video for Arcade Fire's \"We Exist\".",
      "popularity": 0.0705,
      "poster_path": null,
      "release_date": "2014-05-16",
      "title": "Arcade Fire: We Exist",
      "video": false,
      "vote_average": 1,
      "vote_count": 1,
      "character": "Lead",
      "credit_id": "688a520100e9d29e74581558",
      "order": 0,
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/h61wnNwIg15qCc5XNfkGvEESFgB.jpg",
      "genre_ids": [
        18,
        35
      ],
      "id": 407,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "Sugar Rush",
      "overview": "Sugar Rush is an Emmy Award–winning British television comedy drama series developed by Shine Limited and broadcast by Channel 4, based on the Julie Burchill novel of the same name. It follows the trials and tribulations of teenager Kim Daniels, who is dealing with all the usual adolescent issues, plus one - she thinks she might be gay.  Her family has recently moved to Brighton from London, and she finds herself with a huge crush on her new best friend, Maria `Sugar' Sweet. Sugar has a bit of a wild side, and frequently gets Kim into trouble, though Kim can find trouble on her own as well. Despite attractions to other girls, and a few attempts at being interested in guys, Kim continues to long for Sugar.",
      "popularity": 1.7034,
      "poster_path": "/YEW7UwhDpVo6N1tpNHGmC9ZjNO.jpg",
      "first_air_date": "2005-06-07",
      "name": "Sugar Rush",
      "vote_average": 6.988,
      "vote_count": 41,
      "character": "Tom",
      "credit_id": "525354c919c295794013c396",
      "episode_count": 5,
      "first_credit_air_date": "2005-06-07",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/qLMfcvdCcCGD2BNLH8b6ZCBuO7D.jpg",
      "genre_ids": [
        10763,
        35
      ],
      "id": 2224,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "The Daily Show",
      "overview": "The World's Fakest News Team tackle the biggest stories in news, politics and pop culture.",
      "popularity": 70.9368,
      "poster_path": "/ixcfyK7it6FjRM36Te4OdblAq4X.jpg",
      "first_air_date": "1996-07-22",
      "name": "The Daily Show",
      "vote_average": 6.4,
      "vote_count": 609,
      "character": "Self",
      "credit_id": "52572b52760ee3776a2da4e1",
      "episode_count": 1,
      "first_credit_air_date": "2012-06-27",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/AaJVYiHTFNeehKde1H4o57m4Gw8.jpg",
      "genre_ids": [
        10764
      ],
      "id": 92611,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "RuPaul's Drag Race UK",
      "overview": "RuPaul has made the trip across the pond in search of a queen with the most charisma, uniqueness, nerve and talent in all the land.",
      "popularity": 7.2827,
      "poster_path": "/AjHMC80XeQlqYA9WjGcYaQaH45R.jpg",
      "first_air_date": "2019-10-03",
      "name": "RuPaul's Drag Race UK",
      "vote_average": 7.1,
      "vote_count": 58,
      "character": "Self - Guest Judge",
      "credit_id": "602900b4a6725400406a24e0",
      "episode_count": 1,
      "first_credit_air_date": "2019-10-03",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/oOrR8zBOXRsGshPHsa345lhNBwj.jpg",
      "genre_ids": [
        80,
        18
      ],
      "id": 11565,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "Trial & Retribution",
      "overview": "Trial & Retribution is a feature-length ITV police procedural television drama series that began in 1997. It was devised and written by Lynda La Plante as a follow-on from her successful television series Prime Suspect. Each episode of the Trial & Retribution series is broadcast over two nights. The 2008 series 10 had 10 episodes, the longest run of the drama so far. The latest series was number 12 which aired in February 2009.",
      "popularity": 5.5053,
      "poster_path": "/k6jgpAh3sfUdL5wGsgDJNkKlsKL.jpg",
      "first_air_date": "1997-10-19",
      "name": "Trial & Retribution",
      "vote_average": 6.8,
      "vote_count": 13,
      "character": "",
      "credit_id": "5258115019c29531db46417b",
      "episode_count": 2,
      "first_credit_air_date": "2007-01-21",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/x9PFD8fWrFcWVCXLdrTy5oaO9YS.jpg",
      "genre_ids": [
        80,
        18,
        9648
      ],
      "id": 128095,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Under the Banner of Heaven",
      "overview": "A devout detective's faith is tested as he investigates a brutal murder that seems to be connected to an esteemed Utah family's spiral into LDS fundamentalism and their distrust in the government.",
      "popularity": 3.2139,
      "poster_path": "/gKyXUkyKRg9LdZzZWRzk0eKD5HJ.jpg",
      "first_air_date": "2022-04-28",
      "name": "Under the Banner of Heaven",
      "vote_average": 7.541,
      "vote_count": 350,
      "character": "Detective Jeb Pyre",
      "credit_id": "60d551c8c1606a0046a5a03e",
      "episode_count": 7,
      "first_credit_air_date": "2022-04-28",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
      "genre_ids": [
        35,
        10767
      ],
      "id": 63770,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "The Late Show with Stephen Colbert",
      "overview": "Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater.",
      "popularity": 24.0402,
      "poster_path": "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
      "first_air_date": "2015-09-08",
      "name": "The Late Show with Stephen Colbert",
      "vote_average": 6.2,
      "vote_count": 334,
      "character": "Self",
      "credit_id": "60d04ad355937b0048bbac16",
      "episode_count": 3,
      "first_credit_air_date": "2021-06-21",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/2RvT5DdSl4OVtLvXauzAo8565kJ.jpg",
      "genre_ids": [
        80,
        18
      ],
      "id": 125419,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "Red Riding",
      "overview": "Red Riding is a British crime drama limited series written by Tony Grisoni, based on the book series of the same name by David Peace. Comprised of the novels 1974 (1999), 1977 (2000), 1980 (2001), and 1983 (2002), with the first, third, and fourth of these became three feature-length television episodes, Red Riding 1974, Red Riding 1980 and Red Riding 1983.\n\nThree epic tales of murder, corruption and obsession. Utilising recurring characters and events, the Red Riding Trilogy recounts three series of gruesome crimes over a turbulent decade in Northern England.",
      "popularity": 1.8054,
      "poster_path": "/y614CZxl5HjN0iae59na5n1Fjui.jpg",
      "first_air_date": "2009-03-05",
      "name": "Red Riding",
      "vote_average": 6.7,
      "vote_count": 8,
      "character": "Eddie Dunford",
      "credit_id": "6415cc6ae7414600821627ec",
      "episode_count": 3,
      "first_credit_air_date": "2009-03-05",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/sSAX59Kf01lBRkBW4UcIL4kIoIm.jpg",
      "genre_ids": [
        35,
        10763
      ],
      "id": 1667,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Saturday Night Live",
      "overview": "A late-night live television sketch comedy and variety show created by Lorne Michaels. The show's comedy sketches, which parody contemporary culture and politics, are performed by a large and varying cast of repertory and newer cast members. Each episode is hosted by a celebrity guest, who usually delivers an opening monologue and performs in sketches with the cast, and features performances by a musical guest.",
      "popularity": 29.852,
      "poster_path": "/s1cZBqbMwAF3w8S3Yo0j5nr2Yuo.jpg",
      "first_air_date": "1975-10-11",
      "name": "Saturday Night Live",
      "vote_average": 6.95,
      "vote_count": 473,
      "character": "Self - Cameo (uncredited)",
      "credit_id": "643be0638ec4ab049aaee31b",
      "episode_count": 1,
      "first_credit_air_date": "2011-11-12",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/7I5VX5Vr1jrUvikA7mTje97dT2e.jpg",
      "genre_ids": [
        10767
      ],
      "id": 2221,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "The View",
      "overview": "ABC Daytime's morning chatfest, currently featuring Whoopi Goldberg, Joy Behar, Sunny Hostin, Sara Haines, Alyssa Farah Griffin, and Ana Navarro discussing the most exciting events of the day. Hot topics in the news, the best experts in their field, celebrity interviews and general entertainment are all part of The View.",
      "popularity": 21.5434,
      "poster_path": "/pEUNIxCMh2jFjUj7u09f4O5CcR4.jpg",
      "first_air_date": "1997-08-11",
      "name": "The View",
      "vote_average": 4.3,
      "vote_count": 106,
      "character": "Self - Guest",
      "credit_id": "6135ef50b7abb50043e49052",
      "episode_count": 2,
      "first_credit_air_date": "2021-09-17",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/upD2G9Z7W07w47c7B8ZqLqbTDc5.jpg",
      "genre_ids": [
        10767
      ],
      "id": 1900,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "LIVE with Kelly and Mark",
      "overview": "A morning talk show with A-list celebrity guests, top-notch performances and one-of-a-kind segments that are unrivaled on daytime television, plus spontaneous, hilarious and unpredictable talk.",
      "popularity": 17.9215,
      "poster_path": "/hBkyypWN3EcOzkozatiCm5VeaG.jpg",
      "first_air_date": "1988-09-05",
      "name": "LIVE with Kelly and Mark",
      "vote_average": 5.4,
      "vote_count": 48,
      "character": "Self",
      "credit_id": "619257e553866e00876204dc",
      "episode_count": 2,
      "first_credit_air_date": "2021-11-18",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/vcFW09U4834DyFOeRZpsx9x1D3S.jpg",
      "genre_ids": [
        10759,
        18,
        10765
      ],
      "id": 57243,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "Doctor Who",
      "overview": "The Doctor is a Time Lord: a 900 year old alien with 2 hearts, part of a gifted civilization who mastered time travel. The Doctor saves planets for a living—more of a hobby actually, and the Doctor's very, very good at it.",
      "popularity": 54.676,
      "poster_path": "/w8enSKCf6Zm0topeQ2XPccDqsqp.jpg",
      "first_air_date": "2005-03-26",
      "name": "Doctor Who",
      "vote_average": 7.573,
      "vote_count": 3236,
      "character": "Frank",
      "credit_id": "61e9c992b513a80044056326",
      "episode_count": 2,
      "first_credit_air_date": "2007-04-21",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/dfX2UaHVE5c7kLBFbgmEZJuy4Ev.jpg",
      "genre_ids": [
        10767,
        35
      ],
      "id": 61818,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Late Night with Seth Meyers",
      "overview": "Seth Meyers, who is \"Saturday Night Live’s\" longest serving anchor on the show’s wildly popular \"Weekend Update,\" takes over as host of NBC’s \"Late Night\" — home to A-list celebrity guests, memorable comedy and the best in musical talent. As the Emmy Award-winning head writer for \"SNL,\" Meyers has established a reputation for sharp wit and perfectly timed comedy, and has gained fame for his spot-on jokes and satire. Meyers takes his departure from \"SNL\" to his new post at \"Late Night,\" as Jimmy Fallon moves to \"The Tonight Show\".",
      "popularity": 51.7645,
      "poster_path": "/jm95V8XjfvqmEhw0MN09wbg9Mi3.jpg",
      "first_air_date": "2014-02-25",
      "name": "Late Night with Seth Meyers",
      "vote_average": 5.261,
      "vote_count": 119,
      "character": "Self",
      "credit_id": "651e7de6f04d0100ffedb476",
      "episode_count": 1,
      "first_credit_air_date": "2022-04-29",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/AvydGD3Y03ad7QLxQ3tAZ3VVkng.jpg",
      "genre_ids": [],
      "id": 27023,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "The Oscars",
      "overview": "An annual American awards ceremony honoring cinematic achievements in the film industry. The various category winners are awarded a copy of a statuette, officially the Academy Award of Merit, that is better known by its nickname Oscar.",
      "popularity": 7.402,
      "poster_path": "/sSsBn4CeTAnSF6uWCwr3zpKknYV.jpg",
      "first_air_date": "1953-03-19",
      "name": "The Oscars",
      "vote_average": 6.961,
      "vote_count": 76,
      "character": "Self",
      "credit_id": "624274bbd71fb40047f77cbd",
      "episode_count": 2,
      "first_credit_air_date": "2022-03-27",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/riAGbIUpWdLJckBdI8McejwqLG5.jpg",
      "genre_ids": [
        10767
      ],
      "id": 105197,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Variety Studio: Actors on Actors",
      "overview": "PBS SoCal and Variety take you inside the biggest movies and TV shows of the past year through candid conversations with today's hottest actors. Hosted by Variety Film Awards Editor Clayton Davis and Variety Chief Correspondent Elizabeth Wagmeister, each episode brings together pairs of actors engaging in intimate one-on-one discussions about their craft and work.",
      "popularity": 17.1216,
      "poster_path": "/pgWZXYG0gTKkwRH9pTxoscFmq4H.jpg",
      "first_air_date": "2014-12-21",
      "name": "Variety Studio: Actors on Actors",
      "vote_average": 4.6,
      "vote_count": 10,
      "character": "Self",
      "credit_id": "657d66015f2db106d8ddafb9",
      "episode_count": 4,
      "first_credit_air_date": "2017-01-04",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/7VO04TtL1jIT6XOPs9u4jdB8KaB.jpg",
      "genre_ids": [
        35,
        10767
      ],
      "id": 59941,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "The Tonight Show Starring Jimmy Fallon",
      "overview": "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
      "popularity": 64.3646,
      "poster_path": "/w45SzixehUuyVF4RY9aeNl3sFdc.jpg",
      "first_air_date": "2014-02-17",
      "name": "The Tonight Show Starring Jimmy Fallon",
      "vote_average": 5.9,
      "vote_count": 360,
      "character": "Self",
      "credit_id": "62c848e4498bc200dc6663fe",
      "episode_count": 1,
      "first_credit_air_date": "2014-05-01",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/o3X4ps6mkFLqtKgMq8d4uhgxQXn.jpg",
      "genre_ids": [
        99
      ],
      "id": 14131,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "Simon Schama's Power of Art",
      "overview": "Documentary series in which historian Simon Schama recounts the story of eight moments of high drama in the making of eight artistic masterpieces.",
      "popularity": 0.6859,
      "poster_path": "/7rjzgwQAPlauv5AOHmo8DTP8oxQ.jpg",
      "first_air_date": "2006-10-19",
      "name": "Simon Schama's Power of Art",
      "vote_average": 8.2,
      "vote_count": 16,
      "character": "Boy with Fruit",
      "credit_id": "62debc2e1dbc8806731578ca",
      "episode_count": 1,
      "first_credit_air_date": "2006-10-19",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/sSAX59Kf01lBRkBW4UcIL4kIoIm.jpg",
      "genre_ids": [
        35,
        10763
      ],
      "id": 1667,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Saturday Night Live",
      "overview": "A late-night live television sketch comedy and variety show created by Lorne Michaels. The show's comedy sketches, which parody contemporary culture and politics, are performed by a large and varying cast of repertory and newer cast members. Each episode is hosted by a celebrity guest, who usually delivers an opening monologue and performs in sketches with the cast, and features performances by a musical guest.",
      "popularity": 29.852,
      "poster_path": "/s1cZBqbMwAF3w8S3Yo0j5nr2Yuo.jpg",
      "first_air_date": "1975-10-11",
      "name": "Saturday Night Live",
      "vote_average": 6.95,
      "vote_count": 473,
      "character": "Self - Host",
      "credit_id": "5bf13d530e0a26266b05a642",
      "episode_count": 1,
      "first_credit_air_date": "2014-05-03",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [
        35
      ],
      "id": 245639,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "Swinging",
      "overview": "Sketch show exploring the unique British attitude towards sex and relationships.",
      "popularity": 1.142,
      "poster_path": "/t9D2R1dBuKK3WHoyzx8Q6r1R9bv.jpg",
      "first_air_date": "2005-09-09",
      "name": "Swinging",
      "vote_average": 6,
      "vote_count": 1,
      "character": "Various Roles",
      "credit_id": "65c156aa1dbc8801631ea32d",
      "episode_count": 1,
      "first_credit_air_date": "2005-09-09",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/2pJYis3LUEgFC3UErTQVgmUV1hN.jpg",
      "genre_ids": [
        35,
        10767
      ],
      "id": 1220,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "The Graham Norton Show",
      "overview": "Each week celebrity guests join Irish comedian Graham Norton to discuss what's being going on around the world that week. The guests poke fun and share their opinions on the main news stories. Graham is often joined by a band or artist to play the show out.",
      "popularity": 39.0747,
      "poster_path": "/vrbqaBXB8AALynQzpWz6JdCPEJS.jpg",
      "first_air_date": "2007-02-22",
      "name": "The Graham Norton Show",
      "vote_average": 7.179,
      "vote_count": 274,
      "character": "Self",
      "credit_id": "5de74a327646fd0011980ab5",
      "episode_count": 4,
      "first_credit_air_date": "2014-04-11",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/gpDkx5Mog0jISp5rI7YbxQPKnCK.jpg",
      "genre_ids": [
        10767
      ],
      "id": 63498,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Close Up with The Hollywood Reporter",
      "overview": "Some of this year's most talked about talent open up about the challenges and triumphs of creating critically acclaimed series and performances.",
      "popularity": 12.436,
      "poster_path": "/h7X59O3T4VWVAUzZ00LEpbwA3GP.jpg",
      "first_air_date": "2015-08-02",
      "name": "Close Up with The Hollywood Reporter",
      "vote_average": 6.184,
      "vote_count": 19,
      "character": "Self",
      "credit_id": "5e40261341465c0018cbf8fe",
      "episode_count": 1,
      "first_credit_air_date": "2017-01-22",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/qI8PwP7R7Fbn78wocvkbFESvjbl.jpg",
      "genre_ids": [
        10767
      ],
      "id": 102758,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Off Camera with Sam Jones",
      "overview": "Photographer and director Sam Jones sits down with the myriad professionals of television and movies, and other celebrities (great skateboarders, for example), to discuss their development before fame, their passions beyond their careers, and gives them a space to open up about their insight into their business and their own abilities. Filmed in black and white, with a few deep cushion chairs and sparse set, the show relies on Sam's ability to relate to the guests and their will to speak freely with him.",
      "popularity": 9.4318,
      "poster_path": "/wFzCudeLabyjvwh0n5C9rEtCqVy.jpg",
      "first_air_date": "2014-02-06",
      "name": "Off Camera with Sam Jones",
      "vote_average": 4,
      "vote_count": 4,
      "character": "Self",
      "credit_id": "5ea980e9945d36001f84f77d",
      "episode_count": 1,
      "first_credit_air_date": "2016-12-19",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/qTPAAWDOL6U7ZFQXu1p5b8PLnea.jpg",
      "genre_ids": [
        10767,
        35
      ],
      "id": 272608,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "Chicken Shop Date",
      "overview": "Amelia Dimoldenberg meets a celebrity guest at a local chicken shop for a date, engaging in casual, awkward, and sometimes flirtatious conversation.",
      "popularity": 4.0872,
      "poster_path": "/yWzqMTpyS6j16uBS4I7Sds02bY1.jpg",
      "first_air_date": "2014-12-03",
      "name": "Chicken Shop Date",
      "vote_average": 6,
      "vote_count": 1,
      "character": "Self - Guest",
      "credit_id": "672cc637a818713bdf4921be",
      "episode_count": 1,
      "first_credit_air_date": "2024-10-18",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/qTPAAWDOL6U7ZFQXu1p5b8PLnea.jpg",
      "genre_ids": [
        10767,
        35
      ],
      "id": 272608,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "Chicken Shop Date",
      "overview": "Amelia Dimoldenberg meets a celebrity guest at a local chicken shop for a date, engaging in casual, awkward, and sometimes flirtatious conversation.",
      "popularity": 4.0872,
      "poster_path": "/yWzqMTpyS6j16uBS4I7Sds02bY1.jpg",
      "first_air_date": "2014-12-03",
      "name": "Chicken Shop Date",
      "vote_average": 6,
      "vote_count": 1,
      "character": "Self - Guest (archive footage)",
      "credit_id": "677ff6392b29a918d04e4c80",
      "episode_count": 1,
      "first_credit_air_date": "2024-11-20",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/k7byA5IV9NjeyxzAbMHhB8mrStq.jpg",
      "genre_ids": [
        10764
      ],
      "id": 282813,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Celebrity Substitute",
      "overview": "Andrew Garfield and Florence Pugh lead acting class. Jordan Chiles fills in for the gym teacher. LISA forms her own dance group. They’re the best in the world at what they do—but teaching elementary school kids how to do it? Harder than it looks. And funny and adorable… but thank goodness the real teacher’s back in charge tomorrow.\n\nHosted by Julian Shapiro-Barnum (Recess Therapy), Celebrity Substitute asks our favorite stars to swap limos for lesson plans and spend a day with an amazing class of public school kids. And, thanks to Amazon, every episode has a few other surprises in store…\n\nMost of all, Celebrity Substitute reminds us to give teachers their flowers. Because substituting for a day is one thing. The ones who do it full time? Absolute heroes. Celebrity Substitute is the ultimate feel-good series that celebrates the importance of education and the power of connection—whether you’re selling out Madison Square Garden or singing backup in your first grade choir.",
      "popularity": 1.6203,
      "poster_path": "/3nzxDZJksC0y3i2ETeSAb0huOZB.jpg",
      "first_air_date": "2024-10-22",
      "name": "Celebrity Substitute",
      "vote_average": 0,
      "vote_count": 0,
      "character": "Self",
      "credit_id": "67921caa749b2bc5b546ff35",
      "episode_count": 1,
      "first_credit_air_date": "2024-10-22",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/AvydGD3Y03ad7QLxQ3tAZ3VVkng.jpg",
      "genre_ids": [],
      "id": 27023,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "The Oscars",
      "overview": "An annual American awards ceremony honoring cinematic achievements in the film industry. The various category winners are awarded a copy of a statuette, officially the Academy Award of Merit, that is better known by its nickname Oscar.",
      "popularity": 7.402,
      "poster_path": "/sSsBn4CeTAnSF6uWCwr3zpKknYV.jpg",
      "first_air_date": "1953-03-19",
      "name": "The Oscars",
      "vote_average": 6.961,
      "vote_count": 76,
      "character": "Self - Presenter",
      "credit_id": "67bfc2f4c5de842b4ba23e47",
      "episode_count": 1,
      "first_credit_air_date": "2025-03-02",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/csZAN2mTQgmNmRyTARfnqJa47QM.jpg",
      "genre_ids": [
        99,
        10751
      ],
      "id": 3956,
      "origin_country": [
        "GB"
      ],
      "original_language": "en",
      "original_name": "Who Do You Think You Are?",
      "overview": "A British genealogy documentary series in which celebrities trace their ancestry, discovering secrets and surprises from their past.",
      "popularity": 6.5741,
      "poster_path": "/v7vzsmEDVDzUgEuiMAMRdyh0abW.jpg",
      "first_air_date": "2004-10-12",
      "name": "Who Do You Think You Are?",
      "vote_average": 6.7,
      "vote_count": 24,
      "character": "Self",
      "credit_id": "6800d943f39c730125d9574f",
      "episode_count": 1,
      "first_credit_air_date": "2025-04-22",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [],
      "id": 291368,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Wild Things",
      "overview": "Two of the greatest showman-magicians in history, along with their white tigers, are tasked with turning Sin City into a family-friendly destination. The duo pushes the concept of illusion versus reality to the extreme, personally and professionally, until tragedy reframes and opens a mystery surrounding their last fateful Las Vegas show.",
      "popularity": 0.4592,
      "poster_path": null,
      "first_air_date": "",
      "name": "Wild Things",
      "vote_average": 0,
      "vote_count": 0,
      "character": "Roy",
      "credit_id": "682264d0752abbbbf85a2df3",
      "episode_count": 1,
      "first_credit_air_date": null,
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/jiSlSDL0PZsd3DeW9832lk7eBsE.jpg",
      "genre_ids": [],
      "id": 71494,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Golden Globe Awards",
      "overview": "An annual awards ceremony recognizing excellence in film and television, both domestic and foreign, bestowed by the Hollywood Foreign Press Association.",
      "popularity": 20.7918,
      "poster_path": "/gYG3SHNKui9ps9RfN4u9MMwpy10.jpg",
      "first_air_date": "1944-01-20",
      "name": "Golden Globe Awards",
      "vote_average": 7.2,
      "vote_count": 17,
      "character": "Self - Presenter",
      "credit_id": "683bec2973da683064d212e5",
      "episode_count": 1,
      "first_credit_air_date": "2025-01-05",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/55tcKzl0gZ0lR1q7TrVJm0h9lkT.jpg",
      "genre_ids": [
        10764,
        10751
      ],
      "id": 2912,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Jeopardy!",
      "overview": "America's favorite quiz show where contestants are presented with general knowledge clues in the form of answers, and must phrase their responses in question form.",
      "popularity": 27.3958,
      "poster_path": "/hfz0IgebqGENG6ZnuqKQKMFk2vy.jpg",
      "first_air_date": "1984-09-10",
      "name": "Jeopardy!",
      "vote_average": 6.9,
      "vote_count": 150,
      "character": "Self - Clue Presenter",
      "credit_id": "690cf7e713e44dda0cdd0eb1",
      "episode_count": 1,
      "first_credit_air_date": "2024-10-21",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/dfX2UaHVE5c7kLBFbgmEZJuy4Ev.jpg",
      "genre_ids": [
        10767,
        35
      ],
      "id": 61818,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Late Night with Seth Meyers",
      "overview": "Seth Meyers, who is \"Saturday Night Live’s\" longest serving anchor on the show’s wildly popular \"Weekend Update,\" takes over as host of NBC’s \"Late Night\" — home to A-list celebrity guests, memorable comedy and the best in musical talent. As the Emmy Award-winning head writer for \"SNL,\" Meyers has established a reputation for sharp wit and perfectly timed comedy, and has gained fame for his spot-on jokes and satire. Meyers takes his departure from \"SNL\" to his new post at \"Late Night,\" as Jimmy Fallon moves to \"The Tonight Show\".",
      "popularity": 51.7645,
      "poster_path": "/jm95V8XjfvqmEhw0MN09wbg9Mi3.jpg",
      "first_air_date": "2014-02-25",
      "name": "Late Night with Seth Meyers",
      "vote_average": 5.261,
      "vote_count": 119,
      "character": "Self - Guest",
      "credit_id": "691aca7dd75824bcf244696d",
      "episode_count": 1,
      "first_credit_air_date": "2024-10-08",
      "media_type": "tv"
    },
    {
      "adult": false,
      "backdrop_path": "/upD2G9Z7W07w47c7B8ZqLqbTDc5.jpg",
      "genre_ids": [
        10767
      ],
      "id": 1900,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "LIVE with Kelly and Mark",
      "overview": "A morning talk show with A-list celebrity guests, top-notch performances and one-of-a-kind segments that are unrivaled on daytime television, plus spontaneous, hilarious and unpredictable talk.",
      "popularity": 17.9215,
      "poster_path": "/hBkyypWN3EcOzkozatiCm5VeaG.jpg",
      "first_air_date": "1988-09-05",
      "name": "LIVE with Kelly and Mark",
      "vote_average": 5.4,
      "vote_count": 48,
      "character": "Self - Guest",
      "credit_id": "691bffafb380fd860081c667",
      "episode_count": 1,
      "first_credit_air_date": "2025-03-28",
      "media_type": "tv"
    }
  ],
  "crew": [
    {
      "adult": false,
      "backdrop_path": "/sPPsR9f4K0movWVQ99u4uMqFzEL.jpg",
      "genre_ids": [
        10749,
        878,
        18
      ],
      "id": 152601,
      "original_language": "en",
      "original_title": "Her",
      "overview": "In the not so distant future, Theodore, a lonely writer, purchases a newly developed operating system designed to meet the user's every need. To Theodore's surprise, a romantic relationship develops between him and his operating system. This unconventional love story blends science fiction and romance in a sweet tale that explores the nature of love and the ways that technology isolates and connects us all.",
      "popularity": 15.0099,
      "poster_path": "/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg",
      "release_date": "2013-12-18",
      "title": "Her",
      "video": false,
      "vote_average": 7.845,
      "vote_count": 14872,
      "credit_id": "61b6d796f9183a001d7cf08d",
      "department": "Crew",
      "job": "Thanks",
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": "/9eYrq3NZq3WsCuYQS0q9zPr1eMf.jpg",
      "genre_ids": [
        35,
        18
      ],
      "id": 557950,
      "original_language": "en",
      "original_title": "Mainstream",
      "overview": "A young woman thinks she’s found a path to internet stardom when she starts making YouTube videos with a charismatic stranger  – until the dark side of viral celebrity threatens to ruin them both.",
      "popularity": 5.8435,
      "poster_path": "/9vTf02WXyldeKN4kfwZRwwI4XbG.jpg",
      "release_date": "2021-05-07",
      "title": "Mainstream",
      "video": false,
      "vote_average": 6.3,
      "vote_count": 361,
      "credit_id": "5fa6829e43494f00401cc4d9",
      "department": "Production",
      "job": "Producer",
      "media_type": "movie"
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [],
      "id": 291368,
      "origin_country": [
        "US"
      ],
      "original_language": "en",
      "original_name": "Wild Things",
      "overview": "Two of the greatest showman-magicians in history, along with their white tigers, are tasked with turning Sin City into a family-friendly destination. The duo pushes the concept of illusion versus reality to the extreme, personally and professionally, until tragedy reframes and opens a mystery surrounding their last fateful Las Vegas show.",
      "popularity": 0.4592,
      "poster_path": null,
      "first_air_date": "",
      "name": "Wild Things",
      "vote_average": 0,
      "vote_count": 0,
      "credit_id": "682266e7c9d49e83bca16790",
      "department": "Production",
      "episode_count": 1,
      "first_credit_air_date": null,
      "job": "Executive Producer",
      "media_type": "tv"
    }
  ],
  "id": 37625
}